# Generated by Django 3.2.4 on 2021-06-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('HUMANITIES', 'HUMANITIES'), ('EDUCATION', 'EDUCATION'), ('ENVIRONMENT', 'ENVIORNMENT'), ('HEALTH', 'HEALTH'), ('CHARITY', 'CHARITY'), ('RELIGION', 'RELIGION'), ('SERVICES', 'SERVICES'), ('OTHER', 'OTHER')], max_length=100)),
                ('description', models.TextField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
