# Generated by Django 3.2.4 on 2021-06-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_organization_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('HUMANITIES', 'HUMANITIES'), ('EDUCATION', 'EDUCATION'), ('ENVIRONMENT', 'ENVIRONMENT'), ('HEALTH', 'HEALTH'), ('CHARITY', 'CHARITY'), ('RELIGION', 'RELIGION'), ('SERVICES', 'SERVICES'), ('OTHER', 'OTHER')], max_length=100),
        ),
    ]
